- app/build.gradle
- app/src/main/java/com/api/EngineerCollabo/SecurityConfig.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/services/UserService.java
- app/src/main/resources/application.properties
- app/src/main/resources/import.sql
- app/src/main/resources/templates/indexc.html
ログインのセキュリティ機能は実装済み
アカウント登録は特にspring securityで実装する必要はない
#36
> Spring Securityを使ったアカウントAPI、ログインAPI

- app/src/main/java/com/api/EngineerCollabo/SecurityConfig.java
- app/src/main/java/com/api/EngineerCollabo/controllers/RoutingController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Channel.java
- app/src/main/java/com/api/EngineerCollabo/entities/ChatRoom.java
- app/src/main/java/com/api/EngineerCollabo/entities/Directory.java
- app/src/main/java/com/api/EngineerCollabo/entities/File.java
- app/src/main/java/com/api/EngineerCollabo/entities/Follower.java
- app/src/main/java/com/api/EngineerCollabo/entities/Member.java
- app/src/main/java/com/api/EngineerCollabo/entities/Message.java
- app/src/main/java/com/api/EngineerCollabo/entities/Offer.java
- app/src/main/java/com/api/EngineerCollabo/entities/Owner.java
- app/src/main/java/com/api/EngineerCollabo/entities/ProjectNotice.java
- app/src/main/java/com/api/EngineerCollabo/entities/Roll.java
- app/src/main/java/com/api/EngineerCollabo/entities/Skill.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/entities/UserNotice.java
- app/src/main/java/com/api/EngineerCollabo/services/UserService.java
- app/src/main/resources/import.sql
外部キーカラムにnullを許容しないようにentityファイルに設定を追加
#30
> 【バグ】外部キー制約のカラムなのにnullを許容している

- app/src/main/java/com/api/EngineerCollabo/entities/Channel.java
- app/src/main/java/com/api/EngineerCollabo/entities/ChatRoom.java
- app/src/main/java/com/api/EngineerCollabo/entities/Directory.java
- app/src/main/java/com/api/EngineerCollabo/entities/File.java
- app/src/main/java/com/api/EngineerCollabo/entities/Follower.java
- app/src/main/java/com/api/EngineerCollabo/entities/Member.java
- app/src/main/java/com/api/EngineerCollabo/entities/Message.java
- app/src/main/java/com/api/EngineerCollabo/entities/Offer.java
- app/src/main/java/com/api/EngineerCollabo/entities/Owner.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ProjectNotice.java
- app/src/main/java/com/api/EngineerCollabo/entities/Roll.java
- app/src/main/java/com/api/EngineerCollabo/entities/Skill.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/entities/UserNotice.java
> [fixed]lombokの適応および不要importの削除

- app/src/main/java/com/api/EngineerCollabo/controllers/ProjectController.java
- app/src/main/java/com/api/EngineerCollabo/entities/RequestMembers.java
- app/src/main/java/com/api/EngineerCollabo/repositories/MemberRepository.java
> [fixed] memberのcrudAPIの実装

- app/src/main/java/com/api/EngineerCollabo/controllers/UserController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseUser.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/repositories/ProjectRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/ProjectService.java
- app/src/main/java/com/api/EngineerCollabo/services/UserService.java
- app/src/main/resources/import.sql
> #22をmasterにマージ後に出たエラーの修正

- app/src/main/java/com/api/EngineerCollabo/entities/ResponseUser.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/services/UserService.java
> responseUserに足りていないプロパティを追加する #55

- app/src/main/java/com/api/EngineerCollabo/controllers/ProjectController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/UserController.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
>  [fiexed]ログイン、アカウント時にエラーになった理由を出力して欲しい

- app/gradle/wrapper/gradle-wrapper.properties
- app/src/main/java/com/api/EngineerCollabo/controllers/ChannelController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Channel.java
- app/src/main/java/com/api/EngineerCollabo/entities/ChatRoom.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseChannel.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/services/ChannelService.java
- app/src/main/resources/import.sql
> [WIP] feature/issue#21 チャットチャンネルページ遷移APIの実装

- app/src/main/java/com/api/EngineerCollabo/controllers/MessageController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Message.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseMessage.java
- app/src/main/java/com/api/EngineerCollabo/services/MessageService.java
- app/src/main/resources/import.sql
> [WIP]Feature/issue#23メッセージ投稿APIの実装

- app/src/main/java/com/api/EngineerCollabo/controllers/OfferController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Offer.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseOffer.java
- app/src/main/java/com/api/EngineerCollabo/services/OfferService.java
> [fixed]オファーAPIの実装#24

- app/src/main/java/com/api/EngineerCollabo/controllers/OfferController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseOffer.java
- app/src/main/java/com/api/EngineerCollabo/services/OfferService.java
> [fixed]offer APIの Read機能の追加 #75

- app/src/main/java/com/api/EngineerCollabo/controllers/OfferController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/RollController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseRoll.java
- app/src/main/java/com/api/EngineerCollabo/entities/Roll.java
- app/src/main/java/com/api/EngineerCollabo/services/RollService.java
> [fixed]rollのcrud機能 #67

- app/src/main/java/com/api/EngineerCollabo/controllers/SkillController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseSkill.java
- app/src/main/java/com/api/EngineerCollabo/entities/Skill.java
- app/src/main/java/com/api/EngineerCollabo/repositories/SkillRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/SkillService.java
> [fixed]skillsのcrud機能 #68

- app/src/main/java/com/api/EngineerCollabo/controllers/FileController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/MessageController.java
- app/src/main/java/com/api/EngineerCollabo/entities/File.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseFile.java
- app/src/main/java/com/api/EngineerCollabo/repositories/FileRepository.java
- app/src/main/java/com/api/EngineerCollabo/repositories/ProjectRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/FileService.java
- app/src/main/java/com/api/EngineerCollabo/services/ProjectService.java
- app/src/main/resources/import.sql
> [fixed] ファイルテーブルのcrud機能の実装 #69

- app/src/main/java/com/api/EngineerCollabo/controllers/DirectoryController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Directory.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseDirectory.java
- app/src/main/java/com/api/EngineerCollabo/repositories/DirectoryRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/DirectoryService.java
- app/src/main/resources/import.sql
> [fixed]ディレクトリテーブルのcrud機能の実装 #70

- app/src/main/java/com/api/EngineerCollabo/controllers/ProjectNoticeController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ProjectNotice.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseProjectNotice.java
- app/src/main/java/com/api/EngineerCollabo/services/ProjectNoticeService.java
> [fixed]project_noticesのテーブルのcrud機能 #71

- app/src/main/java/com/api/EngineerCollabo/controllers/UserNoticeController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseUserNotice.java
- app/src/main/java/com/api/EngineerCollabo/entities/UserNotice.java
- app/src/main/java/com/api/EngineerCollabo/services/UserNoticeService.java
- app/src/main/resources/import.sql
> [fixed]user_noticesのテーブルのcrud機能 #72

- app/src/main/java/com/api/EngineerCollabo/controllers/FileDownloadController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/FileDownloadController.java.java
- app/src/main/resources/test.txt
> [fixed]ファイルダウンロード（ローカル）APIの実装

- app/src/main/java/com/api/EngineerCollabo/EngineerCollaboApplication.java
- app/src/main/java/com/api/EngineerCollabo/controllers/MessageController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Message.java
Reverts TakeshiAono/preliminary-engineere-collaboration#95
> Revert "[fixed] メッセージEntityにcreatedAtとupdatedAtを追加する"

- app/src/main/java/com/api/EngineerCollabo/controllers/OperationController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/UserNoticeController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Operation.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseOperation.java
- app/src/main/java/com/api/EngineerCollabo/repositories/OperationRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/OperationService.java
- app/src/main/resources/import.sql
> [fixed] 作業履歴テーブルとAPIを追加する

- app/src/main/java/com/api/EngineerCollabo/controllers/ProjectController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/TaskController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseProject.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseTask.java
- app/src/main/java/com/api/EngineerCollabo/entities/Task.java
- app/src/main/java/com/api/EngineerCollabo/entities/User.java
- app/src/main/java/com/api/EngineerCollabo/repositories/TaskRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/ProjectService.java
- app/src/main/java/com/api/EngineerCollabo/services/TaskService.java
- app/src/main/resources/import.sql
- readme.md
> [fixed]タスクテーブルとAPIを作成する

- app/src/main/java/com/api/EngineerCollabo/config/SecurityConfig.java
- app/src/main/java/com/api/EngineerCollabo/config/WebSocketConfig.java
- app/src/main/java/com/api/EngineerCollabo/controllers/TaskController.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseProjectTasks.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseTasks.java
- app/src/main/java/com/api/EngineerCollabo/entities/Task.java
- app/src/main/java/com/api/EngineerCollabo/initializer/TaskInitializer.java
- app/src/main/java/com/api/EngineerCollabo/repositories/TaskRepository.java
- app/src/main/java/com/api/EngineerCollabo/repositories/UserRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/UserService.java
> [WIP]projectに属するタスクを取得するAPIを実装する

- app/src/main/java/com/api/EngineerCollabo/controllers/MilestoneController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/TaskController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Milestone.java
- app/src/main/java/com/api/EngineerCollabo/entities/Project.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseMilestone.java
- app/src/main/java/com/api/EngineerCollabo/entities/Task.java
- app/src/main/java/com/api/EngineerCollabo/initializer/TaskInitializer.java
- app/src/main/resources/import.sql
> #100 マイルストーンテーブルとAPIを作成する。

- app/src/main/java/com/api/EngineerCollabo/controllers/OfferController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Milestone.java
> #130 OfferControllerに@CrossOrigin追加

- docker-compose.yml
Reverts TakeshiAono/preliminary-engineere-collaboration#148
> Revert "タイポ修正"

- docker-compose.yml
Reverts TakeshiAono/preliminary-engineere-collaboration#147
> Revert "デプロイ用に設定を変更"

- app/src/main/java/com/api/EngineerCollabo/controllers/TaskController.java
パラメータの受け取り方を修正
- 全件表示に対応するため､パラメータが存在しない場合を許容
- パラメータが存在する場合のみ絞り込みを行う
projectId, userId, milestoneId以外のパラメータを受け取れるよう修正すること
> #34 task一覧画面を作る

- app/src/main/java/com/api/EngineerCollabo/controllers/FileDownloadController.java
- app/src/test/java/com/api/EngineerCollabo/controllers/ChannelControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/ChatControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/DirectoryControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/FileControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/FileDownloadControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/MessageControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/MilestoneControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/OfferControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/OperationControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/ProjectControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/ProjectNoticeControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/RoleControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/RoutingControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/SkillControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/TaskControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/UserControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/UserNoticeControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/WebsocketControllerTest.java
- readme.md
コントローラのテストを追加
中身は適当にChatGPTで作っただけなので､間違いがあるかも
close [#132](https://github.com/TakeshiAono/preliminary-engineere-collaboration/issues/132)
> #132_コントローラのテストを追加

- .github/workflows/gradle-test.yaml
- app/build.gradle
- app/src/test/java/com/api/EngineerCollabo/EngineerCollaboApplicationTests.java
- app/src/test/java/com/api/EngineerCollabo/controllers/ChatControllerTest.java
- app/src/test/java/com/api/EngineerCollabo/controllers/FileDownloadControllerTest.java
- app/src/test/resources/application-test.properties
> GitHub Actions でCI環境構築

- app/src/main/java/com/api/EngineerCollabo/controllers/OfferController.java
- app/src/main/java/com/api/EngineerCollabo/controllers/UserNoticeController.java
- app/src/main/java/com/api/EngineerCollabo/entities/Offer.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseOffer.java
- app/src/main/java/com/api/EngineerCollabo/entities/ResponseUserNotice.java
- app/src/main/java/com/api/EngineerCollabo/entities/UserNotice.java
- app/src/main/java/com/api/EngineerCollabo/repositories/ProjectRepository.java
- app/src/main/java/com/api/EngineerCollabo/repositories/UserNoticeRepository.java
- app/src/main/java/com/api/EngineerCollabo/services/OfferService.java
- app/src/main/java/com/api/EngineerCollabo/services/ProjectService.java
- app/src/main/java/com/api/EngineerCollabo/services/UserNoticeService.java
- app/src/main/resources/import.sql
- app/src/test/java/com/api/EngineerCollabo/controllers/UserNoticeControllerTest.java
> オファー受信時の処理 #157

- app/src/main/java/com/api/EngineerCollabo/controllers/TaskController.java
- app/src/main/java/com/api/EngineerCollabo/repositories/TaskRepository.java
- app/src/test/java/com/api/EngineerCollabo/controllers/TaskControllerTest.java
- メソッド名を実態に合わせてputからpatchに修正
- テストが動くよう修正
- パスパラメータのidのoptionalを削除
- deleteメソッドでパスパラメータのidのoptionalを削除
> タスク編集モーダルに合わせてコントローラの不具合を修正

- app/src/main/java/com/api/EngineerCollabo/controllers/ChannelController.java
関連PRおよび概要
https://github.com/TakeshiAono/vue-preliminary-entineer-colabo/pull/83
> [fixed]プロジェクト詳細画面の実装
